"""empty message

Revision ID: 302ed97cea65
Revises: 2aff6775774a
Create Date: 2020-09-06 13:14:51.363322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302ed97cea65'
down_revision = '2aff6775774a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'quantity_in_cart',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'quantity_in_cart',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
