"""empty message

Revision ID: 94ca9cb5a388
Revises: 98f40cf45054
Create Date: 2020-09-08 00:29:07.822847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ca9cb5a388'
down_revision = '98f40cf45054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellerorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('seller_order')
    op.add_column('product', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('seller_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'sellerorder', ['seller_order_id'], ['id'])
    op.create_foreign_key(None, 'product', 'cart', ['cart_id'], ['id'])
    op.create_foreign_key(None, 'product', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'seller_order_id')
    op.drop_column('product', 'order_id')
    op.drop_column('product', 'cart_id')
    op.create_table('seller_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('total', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sellerorder')
    # ### end Alembic commands ###
