"""empty message

Revision ID: 98f40cf45054
Revises: 302ed97cea65
Create Date: 2020-09-07 13:23:47.229701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f40cf45054'
down_revision = '302ed97cea65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity_in_cart', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('quantity_placed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'quantity_placed')
    op.drop_column('product', 'quantity_in_cart')
    # ### end Alembic commands ###
